controller_manager:
    ros__parameters:
        update_rate: 1000 # Hz

        joint_state_broadcaster:
            type: joint_state_broadcaster/JointStateBroadcaster
        joint_trajectory_controller:
            type: joint_trajectory_controller/JointTrajectoryController

joint_trajectory_controller:
    ros__parameters:
        joints:
            - base_x_stage_joint
            - x_y_stage_joint
            - y_z_stage_joint
        command_interfaces:
            - position
        state_interfaces:
            - position
            - velocity
